"""Obsidian vault layout + minimal .obsidian configuration (Graph View color groups).

The vault is a plain folder. Obsidian is NOT required to be running for generation.
"""
from __future__ import annotations

import json
from pathlib import Path

VAULT_FOLDERS = {
    "SITE": "00-Sites", "PAGE": "01-Pages", "POST": "02-Posts", "CATEGORY": "03-Categories", "TAG": "04-Tags",
    "BRAND": "05-Brands", "MODEL": "06-Models", "SERVICE": "07-Services", "LOCATION": "08-Locations",
    "QUERY": "09-Queries", "SCHEMA": "10-Schemas", "SEO_PROBLEM": "11-Problems", "SEO_OPPORTUNITY": "12-Opportunities",
    "REPORT": "99-Reports",
}

# Graph View color groups (query -> color). Colors are Obsidian rgb ints.
GRAPH_GROUPS = [
    ("path:00-Sites", 0xE74C3C), ("path:01-Pages", 0x3498DB), ("path:02-Posts", 0x5DADE2), ("path:03-Categories", 0xF39C12),
    ("path:04-Tags", 0xF7DC6F), ("path:05-Brands", 0x8E44AD), ("path:06-Models", 0xAF7AC5), ("path:07-Services", 0x27AE60),
    ("path:08-Locations", 0x1ABC9C), ("path:09-Queries", 0x95A5A6), ("path:10-Schemas", 0x7F8C8D), ("path:11-Problems", 0xC0392B),
    ("path:12-Opportunities", 0x2ECC71),
]


def ensure_vault(vault: Path) -> dict:
    created = []
    vault.mkdir(parents=True, exist_ok=True)
    for folder in VAULT_FOLDERS.values():
        p = vault / folder
        if not p.exists():
            p.mkdir(parents=True)
            created.append(folder)
    obs = vault / ".obsidian"
    obs.mkdir(exist_ok=True)
    app = obs / "app.json"
    if not app.exists():
        app.write_text(json.dumps({"alwaysUpdateLinks": False, "newLinkFormat": "shortest", "useMarkdownLinks": False,
                                   "showFrontmatter": True, "attachmentFolderPath": "./_attachments"}, indent=2), encoding="utf-8")
        created.append(".obsidian/app.json")
    graph = obs / "graph.json"
    if not graph.exists():
        graph.write_text(json.dumps({
            "collapse-filter": False, "search": "", "showTags": False, "showAttachments": False, "hideUnresolved": True,
            "showOrphans": True, "collapse-color-groups": False,
            "colorGroups": [{"query": q, "color": {"a": 1, "rgb": c}} for q, c in GRAPH_GROUPS],
            "collapse-display": False, "showArrow": True, "textFadeMultiplier": 0, "nodeSizeMultiplier": 1.2,
            "lineSizeMultiplier": 1, "collapse-forces": False, "centerStrength": 0.5, "repelStrength": 12,
            "linkStrength": 1, "linkDistance": 200, "scale": 1, "close": False,
        }, indent=2), encoding="utf-8")
        created.append(".obsidian/graph.json")
    core = obs / "core-plugins.json"
    if not core.exists():
        core.write_text(json.dumps({"file-explorer": True, "global-search": True, "graph": True, "backlink": True,
                                    "outgoing-link": True, "tag-pane": True, "properties": True, "page-preview": True,
                                    "note-composer": False, "command-palette": True, "outline": True, "word-count": True,
                                    "file-recovery": True, "switcher": True}, indent=2), encoding="utf-8")
        created.append(".obsidian/core-plugins.json")
    readme = vault / "README.md"
    if not readme.exists():
        readme.write_text("# SEO Knowledge Graph\n\nGenerated vault. Files are regenerated by `scripts/build-graph.py`; "
                          "manual edits inside generated files will be overwritten.\n\nStart at [[00-Sites]] or open Graph View.\n",
                          encoding="utf-8")
        created.append("README.md")
    return {"vault": str(vault), "created": created}
