"""Explicit WordPress publishing with Application Passwords.

This module is intentionally separate from the read-only sync client.  It only runs after a human calls the
Content Brain publish endpoint.  Scheduled posts are created in WordPress with ``status=future`` so their schedule
survives browser navigation, API restarts and container restarts.
"""
from __future__ import annotations

import html
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any, Callable
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import httpx
from bs4 import BeautifulSoup
from sqlalchemy import Engine, text

from .auth import resolve_auth
from ..brain.content.drafts import DraftRepository
from ..brain.content.repository import ContentRepository
from ..db.repositories.base import utcnow
from ..db.repositories.sites import SitesRepository


class PublishingError(RuntimeError):
    def __init__(self, code: str, message: str, status: int = 409, detail: dict[str, Any] | None = None):
        super().__init__(message)
        self.code, self.status, self.detail = code, status, detail or {}


@dataclass(frozen=True)
class Schedule:
    local: datetime
    utc: datetime
    timezone: str

    @property
    def wordpress_date(self) -> str:
        return self.local.replace(tzinfo=None).isoformat(timespec="seconds")

    @property
    def wordpress_date_gmt(self) -> str:
        return self.utc.replace(tzinfo=None).isoformat(timespec="seconds")


def parse_schedule(value: str, timezone_name: str, now: datetime | None = None) -> Schedule:
    """Parse a browser ``datetime-local`` or aware ISO time in the site's configured timezone."""
    try:
        zone = ZoneInfo(timezone_name or "Asia/Tehran")
    except ZoneInfoNotFoundError as exc:
        # Minimal Windows Python installations may not ship the IANA tz database. Iran has used a fixed UTC+03:30
        # offset since abolishing DST in 2022, so the platform default remains exact without an extra tzdata package.
        if (timezone_name or "Asia/Tehran") == "Asia/Tehran":
            zone = timezone(timedelta(hours=3, minutes=30), name="Asia/Tehran")
        else:
            raise PublishingError("invalid_timezone", f"منطقه زمانی سایت معتبر نیست: {timezone_name}", 422) from exc
    try:
        parsed = datetime.fromisoformat((value or "").strip().replace("Z", "+00:00"))
    except ValueError as exc:
        raise PublishingError("invalid_schedule", "تاریخ و ساعت زمان‌بندی معتبر نیست.", 422) from exc
    local = parsed.replace(tzinfo=zone) if parsed.tzinfo is None else parsed.astimezone(zone)
    utc = local.astimezone(timezone.utc)
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    if utc <= current:
        raise PublishingError("schedule_in_past", "زمان انتشار باید در آینده باشد.", 422)
    return Schedule(local=local, utc=utc, timezone=timezone_name or "Asia/Tehran")


def _inline_markdown(value: str) -> str:
    escaped = html.escape(value)
    escaped = re.sub(r"\[([^\]]+)\]\((https?://[^\s)]+)\)", r'<a href="\2">\1</a>', escaped)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", escaped)
    return escaped


def _markdown_html(body: str) -> str:
    """Dependency-free renderer for the subset generated by our article pipeline (headings, lists, links, emphasis)."""
    out: list[str] = []
    list_kind: str | None = None
    paragraph: list[str] = []

    def flush_paragraph() -> None:
        if paragraph:
            out.append(f"<p>{'<br>'.join(_inline_markdown(x) for x in paragraph)}</p>")
            paragraph.clear()

    def close_list() -> None:
        nonlocal list_kind
        if list_kind:
            out.append(f"</{list_kind}>")
            list_kind = None

    for raw in body.splitlines():
        line = raw.strip()
        if not line:
            flush_paragraph(); close_list(); continue
        heading = re.match(r"^(#{1,6})\s+(.+)$", line)
        bullet = re.match(r"^[-*+]\s+(.+)$", line)
        numbered = re.match(r"^\d+[.)]\s+(.+)$", line)
        if heading:
            flush_paragraph(); close_list(); level = len(heading.group(1)); out.append(f"<h{level}>{_inline_markdown(heading.group(2))}</h{level}>")
        elif bullet or numbered:
            flush_paragraph(); wanted = "ul" if bullet else "ol"
            if list_kind != wanted:
                close_list(); list_kind = wanted; out.append(f"<{wanted}>")
            out.append(f"<li>{_inline_markdown((bullet or numbered).group(1))}</li>")
        elif line.startswith("> "):
            flush_paragraph(); close_list(); out.append(f"<blockquote>{_inline_markdown(line[2:])}</blockquote>")
        else:
            close_list(); paragraph.append(line)
    flush_paragraph(); close_list()
    return "\n".join(out)


def draft_html(body: str, fmt: str, title: str | None = None) -> str:
    """Convert the stored draft to WordPress HTML and remove a duplicate top-level H1.

    WordPress themes render the post title as H1.  Keeping the generated Markdown H1 in the body produces a
    duplicate H1 and a visibly repeated title, so only the first body H1 is removed.
    """
    if fmt == "html":
        rendered = body
    elif fmt == "text":
        rendered = "\n".join(f"<p>{html.escape(line)}</p>" for line in body.splitlines() if line.strip())
    else:
        rendered = _markdown_html(body)
    soup = BeautifulSoup(rendered, "lxml")
    first_h1 = soup.find("h1")
    if first_h1:
        first_h1.decompose()
    root = soup.body or soup
    return "".join(str(x) for x in root.contents).strip()


class WordPressWriter:
    """Small authenticated REST writer.  Credentials are resolved at call time and never persisted here."""

    def __init__(self, wp_url: str, site_id: str, client_factory: Callable[..., httpx.Client] | None = None):
        auth = resolve_auth(site_id)
        if not auth:
            raise PublishingError("wordpress_auth_required", "برای انتشار، نام کاربری و Application Password وردپرس را در اتصال سایت ثبت کنید.", 409)
        self.base = wp_url.rstrip("/") + "/wp-json/wp/v2"
        factory = client_factory or httpx.Client
        self.http = factory(auth=auth.basic, timeout=30, follow_redirects=True,
                            headers={"User-Agent": "SEO-Brain/0.2 (explicit-publisher)", "Accept": "application/json"})

    def close(self) -> None:
        self.http.close()

    def _json(self, method: str, route: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:
        try:
            response = self.http.request(method, self.base + route, json=payload)
        except httpx.TimeoutException as exc:
            raise PublishingError("wordpress_timeout", "وردپرس در زمان مقرر پاسخ نداد.", 504) from exc
        except httpx.RequestError as exc:
            raise PublishingError("wordpress_unreachable", f"اتصال به وردپرس برقرار نشد ({exc.__class__.__name__}).", 502) from exc
        if response.status_code >= 400:
            try:
                raw = response.json()
                wp_code = str(raw.get("code") or "")
                wp_message = str(raw.get("message") or "")
            except ValueError:
                wp_code, wp_message = "", ""
            if response.status_code == 401:
                raise PublishingError("wordpress_not_authorized", "Application Password یا نام کاربری وردپرس نادرست است.", 401)
            if response.status_code == 403:
                raise PublishingError("wordpress_forbidden", "کاربر وردپرس مجوز ایجاد یا انتشار نوشته را ندارد.", 403, {"wp_code": wp_code})
            raise PublishingError("wordpress_write_failed", f"وردپرس درخواست انتشار را نپذیرفت (HTTP {response.status_code}).", 502,
                                  {"wp_code": wp_code, "wp_message": wp_message[:240], "status_code": response.status_code})
        try:
            data = response.json()
        except ValueError as exc:
            raise PublishingError("wordpress_invalid_response", "پاسخ انتشار وردپرس JSON معتبر نیست.", 502) from exc
        if not isinstance(data, dict):
            raise PublishingError("wordpress_invalid_response", "ساختار پاسخ انتشار وردپرس نامعتبر است.", 502)
        return data

    def save_post(self, payload: dict[str, Any], post_id: int | None = None) -> dict[str, Any]:
        return self._json("POST", f"/posts/{post_id}" if post_id else "/posts", payload)

    def get_post(self, post_id: int) -> dict[str, Any]:
        return self._json("GET", f"/posts/{post_id}?context=edit")


def public_post(post: dict[str, Any], schedule: Schedule | None = None) -> dict[str, Any]:
    """Return the stable, non-sensitive subset consumed by the API/UI."""
    return {"wp_post_id": post.get("id"), "status": post.get("status"), "url": post.get("link"),
            "date": post.get("date"), "date_gmt": post.get("date_gmt"), "modified": post.get("modified"),
            "categories": post.get("categories") or [],
            "scheduled_at": schedule.local.isoformat() if schedule else None,
            "scheduled_at_utc": schedule.utc.isoformat().replace("+00:00", "Z") if schedule else None,
            "timezone": schedule.timezone if schedule else None}


class ContentPublisher:
    """Bridge Content Brain's approved draft to the site's real WordPress post."""

    def __init__(self, engine: Engine, writer_factory: Callable[[str, str], WordPressWriter] | None = None):
        self.engine = engine
        self.items = ContentRepository(engine)
        self.drafts = DraftRepository(engine)
        self.sites = SitesRepository(engine)
        self.writer_factory = writer_factory or (lambda url, sid: WordPressWriter(url, sid))

    def _category_ids(self, site_id: str, values: list[int]) -> list[int]:
        wanted = sorted({int(x) for x in values if int(x) > 0})
        if not wanted:
            return []
        marks = ",".join(f":c{i}" for i in range(len(wanted)))
        params = {"s": site_id, **{f"c{i}": value for i, value in enumerate(wanted)}}
        with self.engine.connect() as cx:
            rows = cx.execute(text(f"SELECT wordpress_category_id FROM content_categories WHERE site_id=:s AND source='wordpress' AND wordpress_category_id IN ({marks})"), params).all()
        valid = sorted(int(r[0]) for r in rows if r[0] is not None)
        missing = sorted(set(wanted) - set(valid))
        if missing:
            raise PublishingError("invalid_wordpress_categories", "یک یا چند دسته متعلق به وردپرس این سایت نیست.", 422, {"category_ids": missing})
        return valid

    def publish(self, site_id: str, content_id: int, action: str, category_ids: list[int] | None = None,
                scheduled_at: str | None = None, draft_id: int | None = None) -> dict[str, Any]:
        if action not in {"draft", "publish", "future"}:
            raise PublishingError("invalid_publish_action", "عملیات انتشار معتبر نیست.", 422)
        site = self.sites.get(site_id)
        item = self.items.get(site_id, content_id)
        if not site or not site.wp_url:
            raise PublishingError("wordpress_not_configured", "آدرس وردپرس برای این سایت تنظیم نشده است.", 409)
        if not item:
            raise PublishingError("content_not_found", "محتوا پیدا نشد.", 404)
        draft = self.drafts.get(site_id, draft_id) if draft_id else self.drafts.latest(site_id, content_id)
        if not draft or draft.content_id != content_id:
            raise PublishingError("draft_required", "برای انتشار، ابتدا یک پیش‌نویس محتوا ثبت کنید.", 409)
        if action in {"publish", "future"} and item.status not in {"approved", "published"}:
            raise PublishingError("content_not_approved", "انتشار نهایی فقط بعد از تأیید محتوا مجاز است؛ برای بررسی در وردپرس از پیش‌نویس استفاده کنید.", 409,
                                  {"status": item.status})

        categories = self._category_ids(site_id, category_ids or [])
        schedule = None
        if action == "future":
            if not scheduled_at:
                raise PublishingError("schedule_required", "برای زمان‌بندی، تاریخ و ساعت لازم است.", 422)
            schedule = parse_schedule(scheduled_at, site.timezone or "Asia/Tehran")

        title = (draft.title or item.title).strip()
        payload: dict[str, Any] = {"title": title, "content": draft_html(draft.body, draft.format, title),
                                   "status": action, "slug": item.slug or "", "categories": categories}
        if draft.meta_description:
            payload["excerpt"] = draft.meta_description.strip()
        if schedule:
            payload.update(date=schedule.wordpress_date, date_gmt=schedule.wordpress_date_gmt)

        writer = self.writer_factory(site.wp_url, site_id)
        try:
            post = writer.save_post(payload, item.wp_post_id)
        finally:
            writer.close()
        expected = action
        if post.get("status") != expected:
            raise PublishingError("wordpress_status_mismatch", "وردپرس وضعیت درخواستی را تأیید نکرد.", 502,
                                  {"expected": expected, "actual": post.get("status"), "wp_post_id": post.get("id")})
        if not post.get("id"):
            raise PublishingError("wordpress_invalid_response", "وردپرس شناسه نوشته را برنگرداند.", 502)

        published = public_post(post, schedule)
        meta = dict(item.metadata or {})
        meta["wordpress_category_ids"] = categories
        meta["wordpress_publication"] = {**published, "action": action, "draft_id": draft.id, "updated_at": utcnow()}
        updates: dict[str, Any] = {"wp_post_id": int(post["id"]), "metadata": meta}
        if post.get("link"):
            updates["url"] = post["link"]
        if schedule:
            updates.update(publish_date=schedule.local.date().isoformat(), publish_time=schedule.local.strftime("%H:%M"))
        self.items.update(site_id, content_id, **updates)
        if action == "publish" and item.status != "published":
            self.items.transition(site_id, content_id, "published", actor="wordpress", note=f"WordPress post #{post['id']}", force=True)
        else:
            self.items.add_note(site_id, content_id, f"WordPress {action} post #{post['id']}", actor="wordpress")
        return {**published, "content_id": content_id, "draft_id": draft.id, "action": action}

    def status(self, site_id: str, content_id: int, refresh: bool = True) -> dict[str, Any]:
        site = self.sites.get(site_id)
        item = self.items.get(site_id, content_id)
        if not item:
            raise PublishingError("content_not_found", "محتوا پیدا نشد.", 404)
        saved = dict((item.metadata or {}).get("wordpress_publication") or {})
        if not refresh or not item.wp_post_id:
            return {"configured": bool(site and site.wp_url), "wp_post_id": item.wp_post_id, "publication": saved or None}
        if not site or not site.wp_url:
            raise PublishingError("wordpress_not_configured", "آدرس وردپرس برای این سایت تنظیم نشده است.", 409)
        writer = self.writer_factory(site.wp_url, site_id)
        try:
            post = writer.get_post(item.wp_post_id)
        finally:
            writer.close()
        live = public_post(post)
        meta = dict(item.metadata or {})
        meta["wordpress_publication"] = {**saved, **{k: v for k, v in live.items() if v is not None}, "checked_at": utcnow()}
        updates: dict[str, Any] = {"metadata": meta}
        if post.get("link"):
            updates["url"] = post["link"]
        self.items.update(site_id, content_id, **updates)
        if post.get("status") == "publish" and item.status != "published":
            self.items.transition(site_id, content_id, "published", actor="wordpress", note=f"WordPress confirmed post #{post['id']}", force=True)
        return {"configured": True, "wp_post_id": item.wp_post_id, "publication": meta["wordpress_publication"]}
